### ISSUE TITLE
Implement Correct Link design

### ISSUE THREAD

**Issue by birimbau** [birimbau/token-gated-website-demo#7]
FIGMA: https://www.figma.com/file/RGH8cm3aES4UWLjaprZxVh/Collab.Land-Token-Gated-Website?type=design&node-id=0-1&mode=design&t=0V9QbsoCinLNfEGl-0

**Comment by parv3213** [comment]
I will do this.

**Comment by birimbau** [comment]
@parv3213 addigned the issue to you ;)
